<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>DM_Helper.Spike</RootNamespace>
    <AssemblyName>DM_Helper_Spike</AssemblyName>
    <PlatformTarget>x64</PlatformTarget>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <SelfContained>false</SelfContained>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../DM_Helper.Core/DM_Helper.Core.csproj" />
  </ItemGroup>

</Project>
